### ISSUE TITLE
events.js:167 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by janisii** [aluisiora/routeros-client#5]
Hi,

I get this weird unhandled 'error' event and node server just crash. 
Is this node or routeros-client related?

"node": "v10.4.1"
"routeros-client": "^0.11.0"

events.js:167
       throw er; // Unhandled 'error' event
       ^
RosException: Timed out after 10 seconds
     at Connector.onTimeout (/var/app/node_modules/node-routeros/dist/connector/Connector.js:181:30)
     at Object.onceWrapper (events.js:273:13)
     at Socket.emit (events.js:182:13)
     at Socket._onTimeout (net.js:444:8)
     at ontimeout (timers.js:427:11)
     at tryOnTimeout (timers.js:289:5)
     at listOnTimeout (timers.js:252:5)
     at Timer.processTimers (timers.js:212:10)
Emitted 'error' event at:
     at RouterOSAPI.rosApi.once (/var/app/node_modules/routeros-client/dist/RouterOSClient.js:33:53)
     at Object.onceWrapper (events.js:273:13)
     at RouterOSAPI.emit (events.js:182:13)
     at Connector.connectedErrorListener (/var/app/node_modules/node-routeros/dist/RouterOSAPI.js:103:30)
     at Object.onceWrapper (events.js:273:13)
     at Connector.emit (events.js:182:13)
     at Connector.onTimeout (/var/app/node_modules/node-routeros/dist/connector/Connector.js:181:14)
     at Object.onceWrapper (events.js:273:13)
     at Socket.emit (events.js:182:13)
     at Socket._onTimeout (net.js:444:8)

Thanks for help!

**Comment by aluisiora** [comment]
I haven't tested with node v10, but the error is related to `routeros-client`, are you catching the login promise error?

There are two errors you must catch, one from the promise when you try to connect:
```javascript
api.connect().then((client) => {
    // Connected
}).catch((err) => {
    // Connection error
});

// Or with async/await

try {
    const client = await api.connect();
} catch(err) {
    // Connection error
}
```

The other error occurs when you are connected but for some reason the connection fails:
```javascript
const api = new RouterOSClient({
    ...
});

api.on('error', (err) => {
    // Connection error
});
```

**Comment by janisii** [comment]
Thanks. I will add api.on('error', ..) and let you know, if no more app crashing with Unhandled exception error. 

I was catching errors for connect, but not for the connected connection fail situation.

**Comment by aluisiora** [comment]
Closing due to inactivity.
