### ISSUE TITLE
RosException

### ISSUE THREAD

**Issue by aziz1117** [aluisiora/routeros-client#8]
Hi,
I use this package with node.js using socket.io to communicate with server. I received data perfectly, but after a few seconds my app stoped and show me error.
 RosException
 at Connector.onError (……/node_modules/node-routeros/dist/connector/Connector.js:169:15)
at Socket.emit (events.js:321:20)
at emitErrorNT (internal/streams/destroy.js:84:8)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
name: 'RosException',
errno: -104
}

**Comment by ramwolken9** [comment]
Hi,

I too have similar issue, Could you please look into this  @aluisiora (https://github.com/aluisiora/node-routeros)

Error: RosException: Timed out after 10 seconds
    at RosException (..../node_modules/node-routeros/dist/RosException.js:11:14)
    at onTimeout (..../node_modules/node-routeros/dist/connector/Connector.js:180:33)
    at onceWrapper (events.js:277:12)
    at emit (events.js:189:12)
    at EventEmitter.emit (domain.js:459:22)
    at Socket._onTimeout (net.js:440:7)
    at ontimeout (timers.js:436:10)
    at tryOnTimeout (timers.js:300:4)
    at listOnTimeout (timers.js:263:4)
    at processTimers (timers.js:223:9)

**Comment by aluisiora** [comment]
What version of routerOS are you running?

**Comment by ramwolken9** [comment]
Latest

**Comment by ramwolken9** [comment]
@aluisiora  I observed it is happening when the device go offline without proper disconnection / Sudden poweroff of the device, something like that .

**Comment by aluisiora** [comment]
Closing this since it is related to [this issue](https://github.com/aluisiora/node-routeros/issues/16).
